apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/model-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 